# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5eaa3a08f1256bce9b7ee00c45532f1c0acd15a23a7d4a316274dbef2a0ca143c3ae8e54928fe3bc66b4f00257f121a7d1d647b41ad6bba374e5be476eb9897

test:
  secret_key_base: 159cec46e6dce0ee6f56bd6796dfd25ae48d64faad6b64f861ac740623baf45da36d90336bcbe4ce0c33ff3436022ac13d4404f547b9fe105314df2c45018e36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
